---

- name: Add User
  vars:
    new_ios_user: test
    new_user_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"

    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
    
  gather_facts: false
  hosts: all
  tasks:
    - name: Adding user {{ new_ios_user }}
      ios_config:
        lines:
          - username {{ new_ios_user }} secret {{ new_user_pass }}

    - name: Saving Running ios_config
      ios_config:
        save_when: modified

    - name: Showing User Config
      ios_command:
        commands: show start | inc user
      register: output
    - debug:
        var: output.stdout_lines
